# Generated by Django 3.2.4 on 2021-09-28 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='שם הקטגוריה')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם המוצר')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(5)], verbose_name='מחיר המוצר')),
                ('description', models.TextField(blank=True, verbose_name='תיאור המוצר')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='תמונת המוצר')),
                ('subimage1', models.ImageField(blank=True, upload_to='product_sub_images', verbose_name='תמונה נוספת 1')),
                ('subimage2', models.ImageField(blank=True, upload_to='product_sub_images', verbose_name='תמונה נוספת 2')),
                ('subimage3', models.ImageField(blank=True, upload_to='product_sub_images', verbose_name='תמונה נוספת 3')),
                ('count', models.PositiveIntegerField(blank=True, default=' ', verbose_name='כמות המוצר')),
                ('sale', models.BooleanField(default=False, verbose_name='לעשות מבצע ?')),
                ('sale_price', models.FloatField(validators=[django.core.validators.MinValueValidator(5)], verbose_name='מחיר המבצע')),
                ('hot_product', models.BooleanField(default=False, verbose_name='להוסיף למוצרים חמים ?')),
                ('recomanded_product', models.BooleanField(default=False, verbose_name='להוסיף להמלצות שלי?')),
                ('category', models.ManyToManyField(blank=True, default='uncategorized', related_name='קטגוריות', to='shop.Categorie')),
            ],
        ),
    ]
