# Generated by Django 3.2.4 on 2021-09-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_categorie_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subimage1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subimage2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subimage3',
        ),
    ]
