# Generated by Django 3.2.4 on 2021-06-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210630_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='count',
            field=models.IntegerField(verbose_name='מחיר'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='product_images/', verbose_name='למונה'),
        ),
    ]
