# Generated by Django 3.2.4 on 2021-07-01 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210630_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='count',
            field=models.PositiveIntegerField(verbose_name='כמות המוצר'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, verbose_name='תיאור המוצר'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='product_images/', verbose_name='תמונת המוצר'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(5)], verbose_name='מחיר המוצר'),
        ),
    ]
