# Generated by Django 3.2.4 on 2021-07-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tapStatus',
            field=models.BooleanField(default=False, help_text='decide whether or not this item gets pasted onto the website', verbose_name='tap status'),
        ),
    ]
