# Generated by Django 3.2.4 on 2021-07-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210702_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='שם הקטגוריה')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ManyToManyField(blank=True, default='uncategorized', related_name='קטגוריות', to='shop.Categorie'),
        ),
    ]
