# Generated by Django 3.2.4 on 2021-07-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_hot_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hot_product',
            field=models.BooleanField(default=False, verbose_name='להוסיף למוצרים חמים ?'),
        ),
    ]
