# Generated by Django 3.2.4 on 2021-07-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_hot_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recomanded_product',
            field=models.BooleanField(default=False, verbose_name='להוסיף ל "ההמלצות שלי"?'),
        ),
    ]
