# Generated by Django 3.2.4 on 2021-08-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_recomanded_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='recomanded_product',
            field=models.BooleanField(default=False, verbose_name='להוסיף להמלצות שלי?'),
        ),
    ]
